### ISSUE TITLE
Refactor namespaces

### ISSUE THREAD

**Issue by bryanrcarlson** [cafltar/Caf.Etl#2]
Namespaces in unit test do not follow directory structure.  For example, what should be "Caf.Etl.UnitTests.Nodes.LoggerNet" is currently "Caf.Etl.Nodes.LoggerNet.Tests"

**Comment by bryanrcarlson** [comment]
Also, Nodes.LoggerNet.Transform has two classes "DocuemntDbMeasurementV1Transformer" (and V2) that should be renamed to CosmosDBSqlApiV1Transformer, etc to be consistent with renaming of the models

**Comment by bryanrcarlson** [comment]
Also, consolidate names "IMapper" with "IMap"

**Comment by bryanrcarlson** [comment]
Also, consolidate naming of Mapper classes.  LoggerNet has "MapFromToa5DataTableToCafStandards" whlie Manual has MapFromTidyDataToSampleV2.  LoggerNet states "CafStandard" (whatever that means -- I think it's just Cosmos schema) but Manual has the output class type (which is cosmos schema).

**Comment by benichka** [comment]
Hello,
I can help with the namespace name change and the DocumentDbMeasurement* to CosmosDBSqlApi*. Can I do that with a pull request?

**Comment by bryanrcarlson** [comment]
@benichka, that would be great!  Thank you so much!  Yes, please submit a pull request.  If you create a branch, the naming scheme is simply: {github issue number}-{short description based on issue name}.  In this case it'll be something like "2-refactor-namespaces".

Also, I should mention that all notes and comments have been for myself.  I didn't expect anyone to read any of this :)  So let me know if something in github (or my code) isn't clear or comes off as ramblings of a lunatic.

Thanks!

**Comment by benichka** [comment]
Super, I'll do that then :). No problem for the "personal comments", so far I didn't read something rude :D!

Quick question about the code: when using the method `PhysicalQuantityV1.PhysicalQuantityV1()`, the string "DocumentDbMeasurementTransformer" is used as the _sourceID_. Should it also be renamed to "CosmosDBSqlApiTransformer"? Right now it is used in the tests and in `DocumentDbMeasurementV1Transformer.CreateMeasurementFromVariable()`. Not sure if it will mess with existing data...

**Comment by bryanrcarlson** [comment]
Good catch.  Yes, the string should be updated too.  Hopefully that function never gets used but it's good to be backwards compatible :)  

Thanks!

**Comment by benichka** [comment]
Pull request is done. Please tell me if something is wrong/needs to be changed :).
Thank you for taking the time to discuss it with me!

**Comment by bryanrcarlson** [comment]
@benichka All looks great!  I ran integration tests and all passed.  

Thank you so much for your help!
